// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contract.proto

package via.sdj3.supplier.protobuf;

public interface CategoryGrpcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CategoryGrpc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
