// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contract.proto

package via.sdj3.supplier.protobuf;

public interface ProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string confirmed = 1;</code>
   * @return The confirmed.
   */
  java.lang.String getConfirmed();
  /**
   * <code>string confirmed = 1;</code>
   * @return The bytes for confirmed.
   */
  com.google.protobuf.ByteString
      getConfirmedBytes();
}
