// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contract.proto

package via.sep3.supplier.protobuf;

public final class Contract {
  private Contract() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductGrpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductGrpc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CategoryGrpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CategoryGrpc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016contract.proto\"l\n\013ProductGrpc\022\n\n\002id\030\001 " +
      "\001(\003\022\014\n\004name\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022\r" +
      "\n\005price\030\004 \001(\001\022\037\n\010category\030\005 \001(\0132\r.Catego" +
      "ryGrpc\"\034\n\014CategoryGrpc\022\014\n\004name\030\001 \001(\t\"$\n\017" +
      "ProductResponse\022\021\n\tconfirmed\030\001 \001(\t2:\n\010Sh" +
      "opGrpc\022.\n\014OrderProduct\022\014.ProductGrpc\032\020.P" +
      "roductResponseB\036\n\032via.sep3.supplier.prot" +
      "obufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ProductGrpc_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProductGrpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductGrpc_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Price", "Category", });
    internal_static_CategoryGrpc_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CategoryGrpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CategoryGrpc_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_ProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductResponse_descriptor,
        new java.lang.String[] { "Confirmed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
