// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contract.proto

package via.sep3.supplier.protobuf;

public interface ProductGrpcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductGrpc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>double price = 4;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <code>.CategoryGrpc category = 5;</code>
   * @return Whether the category field is set.
   */
  boolean hasCategory();
  /**
   * <code>.CategoryGrpc category = 5;</code>
   * @return The category.
   */
  via.sep3.supplier.protobuf.CategoryGrpc getCategory();
  /**
   * <code>.CategoryGrpc category = 5;</code>
   */
  via.sep3.supplier.protobuf.CategoryGrpcOrBuilder getCategoryOrBuilder();
}
